[package]
name = "gettic-server"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.7"
mongodb = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bcrypt = "0.15"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"
futures = "0.3"
