(module
  (memory (export "memory") 3)
  (func $pq_keygen (param $seed_ptr i32) (param $seed_len i32) (param $pub_out i32) (param $priv_out i32)
    (local $i i32) (local $e i32) (local $a i32) (local $t i32) (local.set $i (i32.const 0))
    (loop $gen (i32.ge_u (local.get $i) (i32.const 256)) (if (then (return)))
      (local.set $e (i32.load8_u (i32.add (local.get $seed_ptr) (i32.rem_u (local.get $i) (local.get $seed_len)))))
      (local.set $a (i32.add (i32.mul (local.get $i) (i32.const 17)) (i32.const 23)))
      (local.set $a (i32.rem_u (local.get $a) (i32.const 3329)))
      (local.set $t (i32.add (i32.mul (local.get $e) (local.get $a)) (i32.const 1)))
      (local.set $t (i32.rem_u (local.get $t) (i32.const 3329)))
      (i32.store16 (i32.add (local.get $pub_out) (i32.mul (local.get $i) (i32.const 2))) (local.get $t))
      (i32.store16 (i32.add (local.get $priv_out) (i32.mul (local.get $i) (i32.const 2))) (local.get $e))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $gen)))
  (func $pq_encapsulate (param $pub_ptr i32) (param $coin_ptr i32) (param $coin_len i32) (param $ct_out i32) (param $ss_out i32)
    (local $i i32) (local $r i32) (local $m i32) (local $c i32) (local $shared i32) (local.set $shared (i32.const 0)) (local.set $i (i32.const 0))
    (loop $encap (i32.ge_u (local.get $i) (i32.const 32)) (if (then (return)))
      (local.set $r (i32.load8_u (i32.add (local.get $coin_ptr) (i32.rem_u (local.get $i) (local.get $coin_len)))))
      (local.set $m (i32.load16_u (i32.add (local.get $pub_ptr) (i32.mul (i32.rem_u (local.get $r) (i32.const 256)) (i32.const 2)))))
      (local.set $c (i32.add (local.get $m) (local.get $r))) (local.set $c (i32.rem_u (local.get $c) (i32.const 3329)))
      (i32.store16 (i32.add (local.get $ct_out) (i32.mul (local.get $i) (i32.const 2))) (local.get $c))
      (local.set $shared (i32.add (i32.mul (local.get $shared) (i32.const 31)) (local.get $c)))
      (i32.store8 (i32.add (local.get $ss_out) (local.get $i)) (i32.rem_u (local.get $shared) (i32.const 256)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $encap)))
  (func $pq_sign (param $msg_ptr i32) (param $msg_len i32) (param $priv_ptr i32) (param $sig_out i32)
    (local $i i32) (local $hash i32) (local $e i32) (local.set $hash (i32.const 0x67452301)) (local.set $i (i32.const 0))
    (loop $sign (i32.ge_u (local.get $i) (i32.const 64)) (if (then (return)))
      (local.set $e (i32.load8_u (i32.add (local.get $msg_ptr) (i32.rem_u (local.get $i) (local.get $msg_len)))))
      (local.set $hash (i32.add (i32.mul (local.get $hash) (i32.const 33)) (local.get $e)))
      (local.set $hash (i32.xor (local.get $hash) (i32.load16_u (i32.add (local.get $priv_ptr) (i32.mul (i32.rem_u (local.get $i) (i32.const 256)) (i32.const 2))))))
      (i32.store8 (i32.add (local.get $sig_out) (local.get $i)) (i32.rem_u (local.get $hash) (i32.const 256)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $sign)))
  (export "pq_keygen" (func $pq_keygen))
  (export "pq_encapsulate" (func $pq_encapsulate))
  (export "pq_sign" (func $pq_sign)))
