      - name: Sunucu Dosyalarını Sıfırdan İndir ve Kur
        run: |
          cd mc/minecraft
          # Mevcut bozuk olabilecek dosyayı siliyoruz
          rm -f bedrock_server
          # Resmi Linux Bedrock Server'ı çekiyoruz
          wget https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.81.01.zip
          unzip bedrock-server-1.20.81.01.zip
          chmod +x bedrock_server
          echo "Orijinal Bedrock Server indirildi."

      - name: Sunucuyu ve Tüneli Başlat
        run: |
          ./localtonet authtoken AqtbZxleyWAJD0B8iFVCvsrUMkjzO7YKo
          ./localtonet udp 19132 &
          
          echo "Sunucu başlatılıyor..."
          cd mc/minecraft
          export LD_LIBRARY_PATH=.
          # Sunucuyu doğrudan başlatıyoruz ki hata varsa loglara düşsün
          ./bedrock_server
